package io.github.fiol_dev.konstant.core

/**
 * Marks declarations that exist for code generated by the Konstant KSP processor. They may
 * change in any release without notice, so do not use them directly. Generated files opt in.
 */
@RequiresOptIn(
    message = "This is used by Konstant's generated code and may change without notice.",
    level = RequiresOptIn.Level.ERROR,
)
@Retention(AnnotationRetention.BINARY)
@Target(AnnotationTarget.CLASS, AnnotationTarget.FUNCTION, AnnotationTarget.PROPERTY)
public annotation class InternalKonstantApi
