package io.github.fiol_dev.konstant.gradle

import org.gradle.api.GradleException

/** Renders the Kotlin object that embeds baked config files as Konstant sources. */
internal object BakedSourceWriter {

    data class Input(val path: String, val content: String)

    private const val CHUNK = 8_000

    fun render(packageName: String, objectName: String, environment: String, files: List<Input>): String {
        val factories = files.map { factoryFor(it.path) }
        val imports = (listOf("io.github.fiol_dev.konstant.core.ConfigSource") +
            factories.distinct()).sorted()

        return buildString {
            appendLine("// Generated by the Konstant Gradle plugin. Do not edit.")
            appendLine("package $packageName")
            appendLine()
            imports.forEach { appendLine("import $it") }
            appendLine()
            appendLine("/**")
            appendLine(" * Config files baked into the app for environment \"${environment.replace("*/", "* /")}\".")
            appendLine(" * Add them to a loader with `+$objectName.sources`.")
            appendLine(" */")
            appendLine("public object $objectName {")
            appendLine("    public const val ENVIRONMENT: String = ${kotlinString(environment)}")
            appendLine()
            appendLine("    /** Highest priority first: a file baked later overrides earlier ones. */")
            appendLine("    public val sources: List<ConfigSource> by lazy {")
            appendLine("        listOf(")
            for ((file, factory) in files.zip(factories).asReversed()) {
                appendLine("            // ${file.path.replace("\n", " ")}")
                // Split long files: a JVM string constant can't exceed 64 KB
                val literal = chunks(file.content)
                    .joinToString(" +\n                ") { kotlinString(it) }
                appendLine("            ${factory.substringAfterLast('.')}.fromString($literal),")
            }
            appendLine("        )")
            appendLine("    }")
            appendLine("}")
        }
    }

    private fun factoryFor(path: String): String {
        val name = path.substringAfterLast('/').lowercase()
        return when {
            name.endsWith(".toml") -> "io.github.fiol_dev.konstant.toml.TomlSource"
            name.endsWith(".yaml") || name.endsWith(".yml") -> "io.github.fiol_dev.konstant.yaml.YamlSource"
            name.endsWith(".properties") -> "io.github.fiol_dev.konstant.sources.PropertiesSource"
            name == ".env" || name.startsWith(".env.") || name.endsWith(".env") ->
                "io.github.fiol_dev.konstant.sources.DotEnvSource"
            else -> throw GradleException(
                "Can't bake '$path': use a .toml, .yaml, .yml, .properties or .env file"
            )
        }
    }

    /** Splits [s] into pieces of at most [CHUNK] chars without cutting a surrogate pair. */
    fun chunks(s: String): List<String> {
        if (s.isEmpty()) return listOf("")
        val result = mutableListOf<String>()
        var start = 0
        while (start < s.length) {
            var end = minOf(start + CHUNK, s.length)
            if (end < s.length && Character.isHighSurrogate(s[end - 1])) end--
            result += s.substring(start, end)
            start = end
        }
        return result
    }

    fun kotlinString(s: String): String = buildString {
        append('"')
        for (ch in s) {
            when (ch) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '$' -> append("\\$")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> append(ch)
            }
        }
        append('"')
    }
}
